---
version: "2"
services:
  bookstack:
    image: linuxserver/bookstack:latest
    container_name: bookstack
    environment:
      - PUID=1001
      - PGID=1001
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_USER= (YOUR INFO HERE)
      - DB_PASS= (YOUR INFO HERE)
      - DB_DATABASE=bookstackapp
    volumes:
      - /bookstack/config:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: linuxserver/mariadb:latest
    container_name: bookstack_db
    environment:
      - PUID=1001
      - PGID=1001
      - MYSQL_ROOT_PASSWORD= (YOUR INFO HERE)
      - TZ=America/Chicago
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER= (YOUR INFO HERE)
      - MYSQL_PASSWORD= (YOUR INFO HERE)
    volumes:
      - /bookstack/config/DB:/config
    restart: unless-stopped