---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "HomelabTim"
subtitle: "Main Dashboard"
logo: "assets/tools/logonotext.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: '<p>All items on this page are created and owned by HomelabTim<p>' # set false if you want to hide it.

# Enable searchbar
search: true
# Optional: Different hotkey for search, defaults to "/"
# searchHotkey: "Shift"

# Optional theme customization
theme: dark
colors:
  light:
    border-radius: 14px
    highlight-primary: "#000000"
    highlight-secondary: "#462c92"
    highlight-hover: "#000000"
    background: "#000000"
    card-background: "#000000"
    footer-background: "#000000"
    text: "#FFFFFF"
    text-header: "#FFFFFF"
    text-title: "#FFFFFF"
    text-subtitle: "#FFFFFF"
    link: "#FFFFFF"
    link-hover: "#462c92"
    background-image: "url(../assets/img/wall5.jpg)"
  dark:
    border-radius: 14px
    highlight-primary: "#000000"
    highlight-secondary: "#462c92"
    highlight-hover: "#000000"
    background: "#000000"
    card-background: "#000000"
    footer-background: "#000000"
    text: "#FFFFFF"
    text-header: "#FFFFFF"
    text-title: "#FFFFFF"
    text-subtitle: "#FFFFFF"
    link: "#FFFFFF"
    link-hover: "#462c92"
    background-image: "url(../assets/img/wall5.jpg)"

# Optional message
#message:
#  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
#  title: "Demo !"
#  icon: "fa fa-grin"
#  content: "This is a dummy homepage demo."

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
#links:
#  - name: "Contribute"
#    icon: "fab fa-github"
#    url: "https://github.com/GeorgeGedox/HomerGX"
#    target: "_blank" # optional html a tag target attribute
#  - name: "My blog"
#    icon: "fas fa-book"
#    url: "https://georgev.design/blog"
  # this will link to a second homer page that will load config from additionnal-page.yml and keep default config values as in config.yml file
  # see url field and assets/additionnal-page.yml.dist used in this example:
#  - name: "another page!"
#   icon: "fas fa-file-alt"
#    url: "#additionnal-page"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Main Servers"
    icon: "fas fa-cloud"
    items:
      - name: "Proxmox"
        logo: "assets/tools/proxmox.png"
        subtitle: "HP Server"
        tag: "Server"
        url: ""
      - name: "Portainer"
        logo: "assets/tools/portainer.png"
        subtitle: "Docker Manager"
        tag: "Docker"
        url: ""
      - name: "Amazon Web Services"
        logo: "assets/tools/aws.png"
        subtitle: "Cloud Provider"
        tag: "Cloud"
        url: ""
  - name: "Work"
    icon: "fas fa-cloud"
    items:
      - name: "AIMG Dashboard"
        logo: "assets/tools/AIMG-Logo2.png"
        subtitle: "Dashboard for AI Media Group"
        tag: "Dashboard"
        url: ""  
      - name: "Bills"
        logo: "assets/tools/google.png"
        subtitle: "Spreadsheet of Bills"
        tag: "Website"
        url: ""
  - name: "Portfolio"
    icon: "fas fa-cloud"
    items:
      - name: "Main Website"
        logo: "assets/tools/logonotext.png"
        subtitle: "Canva Hosted Website"
        tag: "Website"
        url: ""
      - name: "LinkedIn"
        logo: "assets/tools/Linkedin.png"
        subtitle: "Job Board Website"
        tag: "Website"
        url: ""
      - name: "GitHub"
        logo: "assets/tools/github2.png"
        subtitle: "Coding Website"
        tag: "Website"
        url: ""
  - name: ""
    icon: "fas fa-cloud"
    items:
      - name: ""
        logo: "assets/tools/.png"
        subtitle: ""
        tag: ""
        url: ""
      - name: ""
        logo: "assets/tools/.png"
        subtitle: ""
        tag: ""
        url: ""
      - name: ""
        logo: "assets/tools/.png"
        subtitle: ""
        tag: ""
        url: ""


  - name: "Applications"
    icon: "fas fa-cloud"
    items:
      - name: ""
        logo: "assets/tools/.png"
        subtitle: ""
        tag: ""
        url: ""
      - name: ""
        logo: "assets/tools/.png"
        subtitle: ""
        tag: ""
        url: ""
      - name: ""
        logo: "assets/tools/.png"
        subtitle: ""
        tag: ""
        url: ""
      - name: ""
        logo: "assets/tools/.png"
        subtitle: ""
        tag: ""
        url: ""

  - name: "Applications"
    icon: "fas fa-cloud"
    items:
      - name: ""
        logo: "assets/tools/.png"
        subtitle: ""
        tag: ""
        url: ""
      - name: ""
        logo: "assets/tools/.png"
        subtitle: ""
        tag: ""
        url: ""
      - name: ""
        logo: "assets/tools/.png"
        subtitle: ""
        tag: ""
        url: ""


  - name: "Applications"
    icon: "fas fa-cloud"
    items:
      - name: ""
        logo: "assets/tools/.png"
        subtitle: ""
        tag: ""
        url: ""