---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "HomelabTim"
subtitle: "Main Dashboard"
logo: "assets/tools/logonotext.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: '<p>All items on this page are created and owned by HomelabTim<p>' # set false if you want to hide it.

# Enable searchbar
search: true
# Optional: Different hotkey for search, defaults to "/"
# searchHotkey: "Shift"

# Optional theme customization
theme: dark
colors:
  light:
    border-radius: 14px
    highlight-primary: "#000000"
    highlight-secondary: "#462c92"
    highlight-hover: "#000000"
    background: "#000000"
    card-background: "#000000"
    footer-background: "#000000"
    text: "#FFFFFF"
    text-header: "#FFFFFF"
    text-title: "#FFFFFF"
    text-subtitle: "#FFFFFF"
    link: "#FFFFFF"
    link-hover: "#462c92"
    background-image: "url(../assets/img/wall5.jpg)"
  dark:
    border-radius: 14px
    highlight-primary: "#000000"
    highlight-secondary: "#462c92"
    highlight-hover: "#000000"
    background: "#000000"
    card-background: "#000000"
    footer-background: "#000000"
    text: "#FFFFFF"
    text-header: "#FFFFFF"
    text-title: "#FFFFFF"
    text-subtitle: "#FFFFFF"
    link: "#FFFFFF"
    link-hover: "#462c92"
    background-image: "url(../assets/img/wall5.jpg)"

# Optional message
#message:
#  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
#  title: "Demo !"
#  icon: "fa fa-grin"
#  content: "This is a dummy homepage demo."

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
#links:
#  - name: "Contribute"
#    icon: "fab fa-github"
#    url: "https://github.com/GeorgeGedox/HomerGX"
#    target: "_blank" # optional html a tag target attribute
#  - name: "My blog"
#    icon: "fas fa-book"
#    url: "https://georgev.design/blog"
  # this will link to a second homer page that will load config from additionnal-page.yml and keep default config values as in config.yml file
  # see url field and assets/additionnal-page.yml.dist used in this example:
#  - name: "another page!"
#   icon: "fas fa-file-alt"
#    url: "#additionnal-page"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Main Servers"
    icon: "fas fa-server"
    items:
      - name: "Proxmox"
        logo: "assets/tools/proxmox.png"
        subtitle: "HP Server"
        tag: "Server"
        url: "https://proxmox.homelabtim.com"
      - name: "Portainer"
        logo: "assets/tools/portainer.png"
        subtitle: "Docker Manager"
        tag: "Docker"
        url: "https://portainer.homelabtim.com"
      - name: "Amazon Web Services"
        logo: "assets/tools/aws.png"
        subtitle: "Cloud Provider"
        tag: "Cloud"
        url: "https://us-east-1.console.aws.amazon.com/console/home?region=us-east-1#"
  - name: "Work"
    icon: "fas fa-building"
    items:
      - name: "AIMG Dashboard"
        logo: "assets/tools/AIMG-Logo2.png"
        subtitle: "Dashboard for AI Media Group"
        tag: "Dashboard"
        url: "https://dashboard.aimg.io" 
      - name: "ChatGPT"
        logo: "assets/tools/ChatGPT_logo.svg.png"
        subtitle: "OpenAI ChatGPT"
        tag: "Website"
        url: "https://chat.openai.com" 
      - name: "Bills"
        logo: "assets/tools/google.png"
        subtitle: "Spreadsheet of Bills"
        tag: "Website"
        url: "https://docs.google.com/spreadsheets/d/1SlI5i_7dPbkGRa0h_Puv_SC88QpGKEZoRVrhQDRZxWI/edit#gid=0"
  - name: "Portfolio"
    icon: "fas fa-user-tie"
    items:
      - name: "Main Website"
        logo: "assets/tools/logonotext.png"
        subtitle: "Canva Hosted Website"
        tag: "Website"
        url: "https://homelabtim.com"
      - name: "LinkedIn"
        logo: "assets/tools/Linkedin.png"
        subtitle: "Job Board Website"
        tag: "Website"
        url: "https://www.linkedin.com/in/homelabtim/"
      - name: "GitHub"
        logo: "assets/tools/github2.png"
        subtitle: "Coding Website"
        tag: "Website"
        url: "https://github.com/HomelabTim"
  - name: "Banking"
    icon: "fas fa-landmark"
    items:
      - name: "Chase Bank"
        logo: "assets/tools/chase.png"
        subtitle: "Main Bank"
        tag: "Website"
        url: "https://secure.chase.com/web/auth/dashboard#/dashboard/overview"
      - name: "Square Banking"
        logo: "assets/tools/square2.png"
        subtitle: "Bussiness Bank"
        tag: "Website"
        url: "https://squareup.com/dashboard/"
  - name: "Email"
    icon: "fas fa-envelope"
    items:
      - name: "ProtonMail"
        logo: "assets/tools/proton.png"
        subtitle: "Main Email"
        tag: "Website"
        url: "https://mail.proton.me"
      - name: "Gmail"
        logo: "assets/tools/gmail.png"
        subtitle: "Spam Email"
        tag: "Website"
        url: "https://mail.google.com"
      - name: "Outlook Mail"
        logo: "assets/tools/outlook.png"
        subtitle: "HomelabTim Email"
        tag: "Website"
        url: "https://outlook.office.com/mail/"
  - name: "Networking"
    icon: "fas fa-network-wired"
    items:
      - name: "Cloudflare"
        logo: "assets/tools/Cloudflare.png"
        subtitle: "Main DNS"
        tag: "Website"
        url: "https://dash.cloudflare.com"
      - name: "Cloudflare Tunnels"
        logo: "assets/tools/Cloudflare.png"
        subtitle: "Docker DNS Tunnel"
        tag: "Docker"
        url: "https://one.dash.cloudflare.com"
      - name: "Google Domains"
        logo: "assets/tools/googledomains.png"
        subtitle: "Domain Provider"
        tag: "Website"
        url: "https://domains.google.com/registrar/?internal_linking=true&pli=1"
      - name: "TwinGate"
        logo: "assets/tools/twingate2.png"
        subtitle: "VPN to Home Network"
        tag: "Docker"
        url: "https://homelabtimnetwork.twingate.com"
  - name: "Tools"
    icon: "fas fa-toolbox"
    items:
      - name: "Bitwarden"
        logo: "assets/tools/bitwarden.png"
        subtitle: "Password Manager"
        tag: "Website"
        url: "https://vault.bitwarden.com"
      - name: "Flathub"
        logo: "assets/tools/flathub-logo.png"
        subtitle: "Linux Package Manager"
        tag: "Website"
        url: "https://flathub.org/"
  - name: "Creator Studio"
    icon: "fas fa-video"
    items:
      - name: "YouTube"
        logo: "assets/tools/youtube.png"
        subtitle: "Video Platform"
        tag: "Website"
        url: "https://www.youtube.com/"
      - name: "YouTube Studio"
        logo: "assets/tools/youtube.png"
        subtitle: "YouTube Account Manager"
        tag: "Website"
        url: "https://studio.youtube.com/"
      - name: "Canva"
        logo: "assets/tools/canva.png"
        subtitle: "Editing Website"
        tag: "Website"
        url: "https://www.canva.com/"
  - name: "Streaming Services"
    icon: "fas fa-film"
    items:
      - name: "Netflix"
        logo: "assets/tools/netflix.png"
        subtitle: "Video Streaming Service"
        tag: "Website"
        url: "https://www.netflix.com/browse"
      - name: "Hulu"
        logo: "assets/tools/Hulu.png"
        subtitle: "Video Streaming Service"
        tag: "Website"
        url: "https://www.hulu.com/hub/home"
      - name: "HBO Max"
        logo: "assets/tools/Max_logo.svg"
        subtitle: "Video Streaming Service"
        tag: "Website"
        url: "https://www.max.com/"
      - name: "Disney Plus"
        logo: "assets/tools/disney2.png"
        subtitle: "Video Streaming Service"
        tag: "Website"
        url: "https://www.disneyplus.com/"
      - name: "Apple TV"
        logo: "assets/tools/apple.png"
        subtitle: "Video Streaming Service"
        tag: "Website"
        url: "https://tv.apple.com/"
      - name: "Prime Video"
        logo: "assets/tools/prime.png"
        subtitle: "Video Streaming Service"
        tag: "Website"
        url: "https://www.amazon.com/Amazon-Video/"
      - name: "Peacock"
        logo: "assets/tools/Peacock.png"
        subtitle: "Video Streaming Service"
        tag: "Website"
        url: "https://www.peacocktv.com/"